### ISSUE TITLE
PokeDex_R1 crashes when exit

### ISSUE THREAD

**Issue by IkaEren** [nixxholas/PokeDex-Cplusplus#1]
Benchmark when the PokeDex is launching : ![image](https://cloud.githubusercontent.com/assets/15695623/19753939/8801ed5a-9c3b-11e6-9aea-2efeeef85757.png)

However, when PokeDex is closed from the option (5) : Exit the PokeDex, the application crashes : 
![image](https://cloud.githubusercontent.com/assets/15695623/19753950/961c36de-9c3b-11e6-9db0-14f84e857bfe.png)

**Comment by nixxholas** [comment]
@IkaEren Fixed via [Release 2](https://github.com/nixxholas/PokeDex-Cplusplus/releases/tag/r2)
