### ISSUE TITLE
Slow speed on importing and exporting of Pokemons

### ISSUE THREAD

**Issue by IkaEren** [nixxholas/PokeDex-Cplusplus#2]
Via launching PokeDexR2 for the first time , the launching speed is considerably slower as compared to PokeDexR1. 

This is probably due to the importing and exporting speed of the Pokemons. On importing the Pokemons, the importing speed is around 
896ms ![image](https://cloud.githubusercontent.com/assets/15695623/19758425/9206c04a-9c5a-11e6-9d78-8a8b09a35cae.png) as compared to PokeDexR1 which is around 19ms. 

For the exporting speed, it is also considerably slow as compared to PokeDexR1. PokeDexR2 has an exporting speed of 
7594ms ![image](https://cloud.githubusercontent.com/assets/15695623/19758501/f6f75208-9c5a-11e6-9107-493a6db27cfa.png) as compared to PokeDexR1 which is around 75ms. 

The program is able to close successfully via option (5) 'Exit the Pokemon' which is a good point.

**Comment by nixxholas** [comment]
@IkaEren, This issue is related to the code timer. 

On the previous versions, the timer ran checks on the code to initialize the Pokemon objects and was ignoring the actual initialization of the objects. Thus, the timer was also fixed in this version.
