### ISSUE TITLE
Assertion failed 

### ISSUE THREAD

**Issue by IkaEren** [nixxholas/PokeDex-Cplusplus#3]
On PokeDex R3, Pokedex is unable to launch because of an error 

> Assertion failed: IsObject(), file y:\dsal\1617s2dsal1444728nixholaspokedex\rapidjson/document.h, line 1165 

![image](https://cloud.githubusercontent.com/assets/15695623/19862528/b9047646-9fcb-11e6-9756-a45fb93527c6.png)

**Comment by nixxholas** [comment]
@IkaEren Fixed via R5
